DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "items" CASCADE;
DROP TABLE IF EXISTS "requests";
DROP TABLE IF EXISTS "bookings";

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    available BOOLEAN  NOT NULL,
    owner_id     BIGINT NOT NULL,
    request   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255) NOT NULL,
    requestor_id BIGINT  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requestor FOREIGN KEY (requestor_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_item FOREIGN KEY (requestor_id) REFERENCES items (item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comments_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text   VARCHAR(255)   NOT NULL,
    item_id   BIGINT    NOT NULL,
    author_id BIGINT    NOT NULL,
    created   timestamp NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (comments_id),
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time timestamp NOT NULL,
    end_time   timestamp NOT NULL,
    item_id    BIGINT    NOT NULL,
    booker_id  BIGINT    NOT NULL,
    status     VARCHAR(55)   NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT pk_booker FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
)